export const PROFILE_SET_COLOR = 'PROFILE_SET_COLOR';
export const PROFILE_SET_COLORS = 'PROFILE_SET_COLORS';
export const PROFILE_SET_STATS = 'PROFILE_SET_STATS';
export const PROFILE_RESET_STATS = 'PROFILE_RESET_STATS';
